### ISSUE TITLE
Get curve information

### ISSUE THREAD

**Issue by BenjaminHae** [nabla-c0d3/nassl#10]
Is it possible to get the ECDH server params using nassl? Especially information about the curve?
I tried `DebugSslClient.get_ecdh_param` but this doesn't contain the curve.
![image](https://cloud.githubusercontent.com/assets/7386033/25800899/7aa84134-33eb-11e7-8a1d-65e2a9f47f59.png)

**Comment by nabla-c0d3** [comment]
If it's not already in `get_ecdh_param()` then no. It might be easy to add tho, depending on whether OpenSSL exposes a function to get it.

**Comment by BenjaminHae** [comment]
I solved it by trying to map curves to their parameters - when I've implemented it in a nice way I'll send a pull request to sslyze.

**Comment by iromise** [comment]
@BenjaminHae Hi, Have you already implemented it?

**Comment by BenjaminHae** [comment]
@iromise I've attached what I've done so far to the issue in nassl: https://github.com/nabla-c0d3/nassl/issues/25

**Comment by iromise** [comment]
@BenjaminHae Thanks, I will try to look into it and see if there is anything I can do to merge it into nassl.

**Comment by frankclaassens** [comment]
any update on this?
