### ISSUE TITLE
Extend build_wheels workflow to build macOS arm64 wheels

### ISSUE THREAD

**Issue by nabla-c0d3** [nabla-c0d3/nassl#106]
Now that nassl can be compiled and run natively on macOS arm64 (#105), we need to extend the workflow at https://github.com/nabla-c0d3/nassl/blob/release/.github/workflows/build_wheels.yml so that the corresponding wheels are generated.

**Comment by nabla-c0d3** [comment]
GitHub-hosted runners don't support macos-arm64 runners yet: https://github.com/github/roadmap/issues/528

In the mean time, a script is available to build macOS arm64 wheels locally: https://github.com/nabla-c0d3/nassl/pull/107/files#diff-3a208fee249f7d603518a2611a63be9e2f6afe25451bff24bcadf59b829a36f9R3

I've uploaded macOS arm64 wheels to Pypi as nassl version 5.0.1.

**Comment by fj-dt** [comment]
It's now available: https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by nabla-c0d3** [comment]
The build_wheels.yml does build arm64 wheels for macOS now.
