### ISSUE TITLE
Can nassl use system-provided zlib?

### ISSUE THREAD

**Issue by ZhongRuoyu** [nabla-c0d3/nassl#109]
Hi! Homebrew maintainer here. We noticed nassl is building its own zlib and OpenSSL instead of using the system-provided ones. While the reason for building OpenSSL was justified in #64, I wonder if it is possible not to build its own zlib? Thanks!

**Comment by carlocab** [comment]
Note that the API of Zlib is very stable (which is kind of a requirement given how widely used it is), so there should be essentially no additional maintenance burden from allowing use of a system copy of Zlib.

**Comment by nabla-c0d3** [comment]
Hello!

> essentially no additional maintenance

That's possible (even likely), but I won't have time to add support for customizing the build commands, so that the system-provided Zlib is used instead.
