### ISSUE TITLE
"This repository is over its data quota. Purchase more data packs to restore access."

### ISSUE THREAD

**Issue by jambonrose** [nabla-c0d3/nassl#17]
Hi,
I am unable to clone or pull from Github because of a git-lfs quota.

When I clone:

```console
$ git clone https://github.com/nabla-c0d3/nassl.git .
Cloning into '.'...
remote: Counting objects: 2015, done.
remote: Total 2015 (delta 0), reused 0 (delta 0), pack-reused 2015
Receiving objects: 100% (2015/2015), 800.11 KiB | 1.52 MiB/s, done.
Resolving deltas: 100% (1289/1289), done.
Downloading bin/openssl/darwin64/libcrypto.a (3.51 MB)
Error downloading object: bin/openssl/darwin64/libcrypto.a (cad2581e8c52d078d7e156393a1c78e664c54dd2d9ada76233f806619b7381c8)

Errors logged to /Users/andrew/Development/nassl/.git/lfs/objects/logs/20170723T094525.490493612.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs smudge -- %f' failed 2
error: external filter 'git-lfs smudge -- %f' failed
fatal: bin/openssl/darwin64/libcrypto.a: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

The log file reads:

```
git-lfs/1.4.4 (GitHub; darwin amd64; go 1.7.1)
git version 2.11.0

$ git-lfs smudge -- bin/openssl/darwin64/libcrypto.a
Error downloading object: bin/openssl/darwin64/libcrypto.a (cad2581e8c52d078d7e156393a1c78e664c54dd2d9ada76233f806619b7381c8)

Smudge error: Error downloading cad2581e8c52d078d7e156393a1c78e664c54dd2d9ada76233f806619b7381c8: batch response: http: This repository is over its data quota. Purchase more data packs to restore access.
Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-a-personal-account/: batch response: http: This repository is over its data quota. Purchase more data packs to restore access.
Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-a-personal-account/
[Rest Omitted]
```

The link: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-a-personal-account/

Surprisingly, the same git-lfs assets are used across public repositories, which means that our fork at [jambonsw/nassl](https://github.com/jambonsw/nassl) is also unavailable, and that we have been using your bandwidth. I was unaware of this but feel partly responsible, and would be happy to pay for one git-lfs pack for the next two months ($5 for two months).

**Comment by jambonrose** [comment]
If I were to pay for the git-lfs packs, I would opt to use: https://github.myshopify.com/products/gift-card

**Comment by nabla-c0d3** [comment]
Hello,
Thanks for letting me know. To be honest, I'm very disappointed with how GitHub supports git-lfs for public projects. Charging for storage and bandwidth makes no sense, especially since switching to git-lfs reduces bandwidth usage / cost for GitHub, compared to just storing big files in git. The fact the quotas are for every fork, which I did not know, is even crazier.

But sure, I'll take the gift cards =)
Thanks!

**Comment by jambonrose** [comment]
Hi,
I agree with you that git-lfs leaves a lot to be desired, and I think you raise an excellent point about charging us for something that saves them money. I contacted github via their contact page (because the relevant git-lfs issues were locked) to let them know that their design had put us in this position, but I honestly don't expect to have much of an impact.

I've just emailed you a gift card for $10. Let me know if you've not received it!

**Comment by nabla-c0d3** [comment]
Thanks for the gift card! 
I purchased a data pack so you should be good to go. I'll also contact GitHub about this problem.

**Comment by hktalent** [comment]
+ money so is good

**Comment by dark-N00B** [comment]
Does cloning to local device also consumes the LFS data limit? I just cloned my earlier incomplete project and modified some files and now they are stuck. Not syncing at all!

I last committed to the project more than a month ago (didn't use github for that time being) and the project is sized about 400 MB, so how can my data limit be consumed?

**Comment by qb20nh** [comment]
> Does cloning to local device also consumes the LFS data limit? I just cloned my earlier incomplete project and modified some files and now they are stuck. Not syncing at all!
> 
> I last committed to the project more than a month ago (didn't use github for that time being) and the project is sized about 400 MB, so how can my data limit be consumed?

for me downloading archived fork as a zip worked (Also checked allow downloading lfs files inside repo settings before)
it pauses download for a few seconds before resuming again so wait

**Comment by vajithChamuditha-99** [comment]
I have faced the same problem too. how can i overcome this?

This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by qb20nh** [comment]
> I have faced the same problem too. how can i overcome this?
> 
> This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

1. Fork the repo to one of your users
2. Go to repo settings
3. Find "Include Git LFS objects in archives" under the Archives section and check it
4. Go to the Danger Zone section,  select "Archive this repository"
5. Confirm and authorize.
6. Return to the archived repository.
7. Download as .zip
8. Download will pause for a minute or so before it starts downloading lfs objects. Wait and it should continue.

**Comment by Kirushikesh** [comment]
@qb20nh thanks man. I was searching for the solution for a month your solution helped me a lot.

**Comment by ngocnh22** [comment]
Hi @Kirushikesh

You can share specific sharing how can you do that? 
I have tried many times in the same way but It does not work.

**Comment by qb20nh** [comment]
> Hi @Kirushikesh
> 
> You can share specific sharing how can you do that? I have tried many times in the same way but It does not work.

maybe they patched it, you could still try to fork into your user account and pay for it.
https://github.com/account/billing/data/upgrade?packs=1

**Comment by dkilgore-eightfold** [comment]
I paid for a data pack but still get `batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access` when trying to clone a new fork. What is the solution here?

**Comment by dkilgore-eightfold** [comment]
Is it my fork and my user account that needs the data packs or the source repo?

**Comment by sungengyi** [comment]
> I paid for a data pack but still get `batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access` when trying to clone a new fork. What is the solution here?

Same. Just paid but still can't push. 

If that's the case, can I at least get my money back.  :((((((

**Comment by xiaowangzizhao** [comment]
> I paid for a data pack but still get `batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access` when trying to clone a new fork. What is the solution here?

I met the totally same question,had you save it?
