### ISSUE TITLE
Unclosed sockets

### ISSUE THREAD

**Issue by konklone** [nabla-c0d3/nassl#20]
While using `nassl` (via `sslyze`) inside of a Docker container, I saw this go by:

```
/opt/pyenv/versions/3.6.1-debug/lib/python3.6/site-packages/nassl/ssl_client.py:132: ResourceWarning: unclosed <socket.socket fd=89, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('XX.XX.XX.XX', 45828), raddr=('XX.XX.XX.XX', 443)>
```

The relevant line is here: https://github.com/nabla-c0d3/nassl/blob/master/nassl/ssl_client.py#L132

May not be a big deal at all, but I figured I'd at least document it here, in case it points to something worth cleaning up.

**Comment by nabla-c0d3** [comment]
Should be fixed by https://github.com/nabla-c0d3/sslyze/commit/0650c214e2bfddf3164415e557e309e0c70d8adc
