### ISSUE TITLE
Force linking to libz with LDFLAGS needed

### ISSUE THREAD

**Issue by fabian-z** [nabla-c0d3/nassl#25]
I created an sslyze-git package for the Arch Linux User Repository (AUR) which compiles nassl from source. You can see the package build script here:
https://aur.archlinux.org/packages/ss/sslyze-git/PKGBUILD

After initial build set-up, nassl would compile fine but the tests failed with a python
```Import error /path/to/_nassl.so: undefined symbol: inflate```.
I found that it has not linked _nassl.so to libz (in contrast to your release build), leading to this error.

In order to link it properly, I had to add LDFLAGS to force linking to the invocation of setup_unix.py in buildAll_unix.py:
```LDFLAGS="-Wl,--no-as-needed -lz" python setup_unix.py build```
After specifiying the extra linker flags, the build runs fine and works perfectly with sslyze.

This might happen because libz is not imported/used by the code, so it is not linked because the linker thinks its unneeded. If you want, I can prepare a pull request for this change.

**Comment by nabla-c0d3** [comment]
Hi and thanks for working on an sslyze package! 
This problem is weird because nassl compiles/works fine on Debian 7 (my test platform for Linux builds). Also, if you add -lz , you will be dynamically linking zlib although the library should already be statically linked into nassl (so that OpenSSL can support compression); you shouldn't have to load the system's zlib. My guess is that somehow when building OpenSSL, zlib doesn't get statically linked ?
I will try to get an arch linux VM setup but this might take a while.

**Comment by fabian-z** [comment]
Actually, your release build links to libz dynamically (as seen by ldd 
in nassl-0_10-linux64.zip):

$ ldd _nassl.so
linux-vdso.so.1 (0x00007ffca21d1000)
libz.so.1 => /usr/lib/libz.so.1 (0x00007fd155d8b000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fd155b6e000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007fd1557cb000)
/usr/lib64/ld-linux-x86-64.so.2 (0x00007fd1563d7000)

So I guess the two distributions somehow differ in their linker 
behaviour. The change I proposed only forces dynamic linking to libz, 
even if it is not used by the code.
Strange enough, it won't work for me if I omit this option. If it won't 
hurt for other distributions (didn't test yet), one might imho add this 
to default build options.

Thanks for investigating!

Am 05.04.2015 um 00:49 schrieb Alban Diquet:

**Comment by nabla-c0d3** [comment]
You're right, and this was actually a mistake as zlib is already statically linked into OpenSSL... I just removed the dynamic dependency and it stil works on Debian 7:

    ldd test/nassl/_nassl.so 
	linux-gate.so.1 =>  (0xb77e3000)
	libpthread.so.0 => /lib/i386-linux-gnu/i686/cmov/libpthread.so.0 (0xb75b9000)
	libc.so.6 => /lib/i386-linux-gnu/i686/cmov/libc.so.6 (0xb7456000)
	/lib/ld-linux.so.2 (0xb77e4000)

**Comment by fabian-z** [comment]
I tried updating my package for your recent changes, and unfortunately 
nassl now fails to build for me with the following error:

```
===BUILDING NASSL===
Traceback (most recent call last):
   File "setup_unix.py", line 5, in <module>
     from setup_config import NASSL_SETUP, NASSL_EXT_SETUP
   File "/tmp/sslyze/src/nassl/setup_config.py", line 1, in <module>
     from src import NASSL_VERSION
   File "/tmp/sslyze/src/nassl/src/__init__.py", line 29
     SSL_OP_NO_TICKET = 0x00004000L # No TLS Session Tickets
                                  ^
SyntaxError: invalid syntax
Traceback (most recent call last):
   File "./buildAll_unix.py", line 84, in <module>
     main()
   File "./buildAll_unix.py", line 70, in main
     perform_build_task('NASSL', NASSL_BUILD_TASKS)
   File "/tmp/sslyze/src/nassl/buildAll_config.py", line 35, in 
perform_build_task
     subprocess.check_call(command, shell=True, cwd=cwd)
   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
     raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python setup_unix.py build' 
returned non-zero exit status 1
```

Zlib and OpenSSL build fine, but building nassl instantly fails with the 
above error. Any idea what causes this?


Am 05.04.2015 um 20:28 schrieb Alban Diquet:

**Comment by nabla-c0d3** [comment]
It complains about a syntax error in src/__init__.py although the file seems fine (and works fine)... Are you using Python 2.7? Did you make any change to the code base ?

**Comment by fabian-z** [comment]
I wondered about this, too..
My version of python2 is

Python 2.7.9 (default, Dec 11 2014, 04:42:00)
[GCC 4.9.2] on linux2

Actually I did not change anything. This happens on a freshly cloned 
repository.


Am 05.04.2015 um 21:23 schrieb Alban Diquet:

**Comment by Archstacker** [comment]
Same with whe error in the latest version.
```
===BUILDING NASSL===
Traceback (most recent call last):
  File "setup_unix.py", line 5, in <module>
    from setup_config import NASSL_SETUP, NASSL_EXT_SETUP
  File "/tmp/nassl/setup_config.py", line 1, in <module>
    from src import NASSL_VERSION
  File "/tmp/nassl/src/__init__.py", line 29
    SSL_OP_NO_TICKET = 0x00004000L # No TLS Session Tickets
                                 ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "buildAll_unix.py", line 84, in <module>
    main()
  File "buildAll_unix.py", line 70, in main
    perform_build_task('NASSL', NASSL_BUILD_TASKS)
  File "/tmp/nassl/buildAll_config.py", line 35, in perform_build_task
    subprocess.check_call(command, shell=True, cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python setup_unix.py build' returned non-zero exit status 1
```
Wait for solution.
