### ISSUE TITLE
Name of Elliptic Curves

### ISSUE THREAD

**Issue by ericrange** [nabla-c0d3/nassl#25]
Maybe it would be nice to display the name of the curves.

AND if you consider to find out the DHE and ECDHE public keys, it would be possible to check if the server reuse those Keys.

DHE/ECDHE means "temporary" keys. 
as i suppose so far, it means: you dont need a specific key for your key exchange. for each handshake there will be a new generated key. and if you reuse this "temporary" keys, an attacker could find out about your privat key.

until now, i do not really understand the whole concept behind but it seems to be really bad :D

**Comment by ericrange** [comment]
https://blog.webernetz.net/f5-ssl-profile-single-dh-use-not-working/

**Comment by BenjaminHae** [comment]
I wanted to create a pull request for something similiar some time ago (naming curves and groups used for dh).
The methods are ready, but I couldn't figure out where to put them ;)

I could provide the parts already finished in the first week of next year.

**Comment by nabla-c0d3** [comment]
That would be great!

**Comment by BenjaminHae** [comment]
Now my part is ready. I hope it helps.
[GroupsAndCurves.txt](https://github.com/nabla-c0d3/nassl/files/1710854/GroupsAndCurves.txt)


I’ve made this for my employer
 (cirosec, an information security consulting company located in Germany) who is happy to share the results upstream. We regularly use sslyze and are very thankful for your work on it.

**Comment by nabla-c0d3** [comment]
Implemented in https://github.com/nabla-c0d3/nassl/pull/48
