### ISSUE TITLE
Problems linking to libz

### ISSUE THREAD

**Issue by davidgfnet** [nabla-c0d3/nassl#27]
Hey!

I just compiled the damn thing and got:
ImportError: /home/david/Descargas/nassl/test/nassl/_nassl.so: undefined symbol: zError

It seems to be statically linking to libz.a, which is what we expect, since ldd nassl.so shows no trace of libz. I don't have libz.a in my system, so it must be linking against the internal one.
An "nm" on libz.a shows that zError is there, so I have no idea what could possibly be wrong.

Thoughts?
Thanks!

**Comment by nabla-c0d3** [comment]
This has to do with this change: https://github.com/nabla-c0d3/nassl/commit/a0fe4c59c4ad1334cf67cbe2d9254ed1f6fb4ccd

As a temporary workaround you can re-add libz as dynamic dependency although it shouldn't be needed since it's already statically linked.

**Comment by davidgfnet** [comment]
Yep that works. The thing is that doing that you go back to dynamic linking, doing an ldd on my nassl.so shows that. What is the point of having an static libz, if I may ask?
Also libz.a comes with most linux distributions, by just installing the static version of the lib package.
Thanks for the help!

**Comment by nabla-c0d3** [comment]
OpenSSL needs to be linked with Zlib so we have compression support. Zlib will most likely be available on Linux as a dynamic library but that's not true for all platforms (ie. Windows).

**Comment by davidgfnet** [comment]
Oh I see, I thought there was some other need for static linking. Is it the same for openssl? Otherwise I'd rather link it dynamically and avoid compiling it. BTW I guess you can close this if it's already reported :dancer: 
Thanks!!!

**Comment by nabla-c0d3** [comment]
I wasn't using the right arguments so OpenSSL and Zlib weren't actually statically linked.
