### ISSUE TITLE
Remaining python invocation to be changed to python2.7

### ISSUE THREAD

**Issue by fabian-z** [nabla-c0d3/nassl#29]
Hello!
I submitted a pull request sometime ago to provide compatibility for systems which use python3 as default python. There is one small invocation of "python" instead of "python2.7" left here, which I must have not seen back then:
https://github.com/nabla-c0d3/nassl/blob/master/buildAll_unix.py#L67

So I thought I'd leave you a note. If you want me to provide a pull request, I will gladly contribute. Thank you!

**Comment by nabla-c0d3** [comment]
Thanks and yes, although it's a small change, please open a pull request :)
