### ISSUE TITLE
the latest releases does not include bin/*.a files and broken

### ISSUE THREAD

**Issue by blshkv** [nabla-c0d3/nassl#3]
I have tried to re-download few last releases 14.x 15.x and found that all bin/**/lib*.a files are broken.
They are just small text files with a content similar to the following:
```
version https://git-lfs.github.com/spec/v1
oid sha256:9a6d8ac805a54e10b153028eab00a320241da224011ec36281966640245620b1
size 4851612
```

**Comment by nabla-c0d3** [comment]
I switched to Git LFS to store the binaries, so it is much faster to clone the repo, but it looks like it broke the release files. It should be fixed in the next release.

**Comment by nabla-c0d3** [comment]
Would it be possible to just clone the repo (with Git LFS enabled) instead of downloading the archive?

**Comment by blshkv** [comment]
It is possible for Gentoo but may be a problem for other distros.

**Comment by nabla-c0d3** [comment]
This is because of Git LFS.

**Comment by blshkv** [comment]
well, yes, that's known. Can you fix it so it would be possible to download the tar.gz file with all files?
That's the title of this issue
