### ISSUE TITLE
Error when installing from git clone

### ISSUE THREAD

**Issue by KozbialP** [nabla-c0d3/nassl#34]
I wanted to install newest nassl version, which is required to install sslyze. Newest version in pip is 1.03 so i tried to install from git clone. 
When running command `python sample_client.py` i got error:
`Traceback (most recent call last):
  File "sample_client.py", line 7, in <module>
    from nassl.ssl_client import OpenSslVersionEnum, SslClient
  File "/home/kali/nassl/nassl/ssl_client.py", line 7, in <module>
    from nassl import _nassl  # type: ignore
ImportError: /home/kali/nassl/nassl/_nassl.so: undefined symbol: SSL_SESSION_set_max_early_data`

Building from scratch also didn't work for me. Any ideas what to do with that?

**Comment by nabla-c0d3** [comment]
Which OS and version of Python?

**Comment by KozbialP** [comment]
Kali Linux kernel 4.4.0-43
Python version Python 2.7.14+

**Comment by nabla-c0d3** [comment]
Something is wrong with the nassl Linux wheel for 2.7. If possible you should switch to python 3.6.
