### ISSUE TITLE
"OSError: No such file or directory" when installing with pip

### ISSUE THREAD

**Issue by rdegraaf** [nabla-c0d3/nassl#39]
On Centos 7, attempting to install nassl using pip results in the following error:

    [user@cento7 sslyze]$ pip install -r requirements.txt --target ./lib
    You are using pip version 7.1.0, however version 8.1.0 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Collecting nassl<1.10.0,>=0.13.0 (from -r requirements.txt (line 1))
      Using cached nassl-0.13.4.tar.gz
    Installing collected packages: nassl
      Running setup.py install for nassl
    Successfully installed nassl
    Exception:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
        status = self.run(options, args)
      File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 348, in run
        for item in os.listdir(lib_dir):
    OSError: [Errno 2] No such file or directory: '/tmp/tmpUEmbvL/lib/python'

Despite the `Successfully installed nassl` message, ./lib is empty after that command completes.

Attempting to install on Fedora 22 results in similar error messages (forcing a different version after deleting the pip cache, to see if that made any difference):

    [user@redora22 sslyze]$ pip install nassl==0.13.2 --target ./lib            
    You are using pip version 6.0.8, however version 8.1.0 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.      
    Collecting nassl==0.13.2
      Downloading nassl-0.13.2.tar.gz (13.5MB)
       100% |################################| 13.5MB 41kB/s 
    Installing collected packages: nassl
      Running setup.py install for nassl
        building 'nassl._nassl' extension
        gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python2.7 -c nassl/_nassl/nassl.c -o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl.o -Wall

[further gcc calls elided]

    Successfully installed nassl
    Exception:
    Traceback (most recent call last):                                              
      File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main 
        status = self.run(options, args)                                            
      File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 399, in run                                                                             
        for item in os.listdir(lib_dir):                                            
    OSError: [Errno 2] No such file or directory: '/tmp/tmp5dvdP3/lib/python/'      

Before you ask, Fedora 22 and Centos 7 are both recent releases and those are the most recent pip packages available for them.

**Comment by nabla-c0d3** [comment]
Hi Rennie :)
I only tried this on Debian, but this seems to be an error with your environment maybe ? Are you using a virtualenv ? Can you try upgrading pip ?

**Comment by rdegraaf** [comment]
No, I wasn't running in a virtualenv or any sort of container.  I was just using the latest versions of Python and pip from Fedora and Centos.  The Centos system is a clean install, so there shouldn't be anything unusual about its environment.  

Neither Fedora nor Centos has a more recent pip package to which I could upgrade.

nassl does install for me in Ubuntu 14.04.  However, I was hoping to work on something using my home machine.

**Comment by rdegraaf** [comment]
The problem appears to be that nassl's setup.py is storing everything in $base/**lib64**.  This is then confusing pip, which expects $base/lib.

    [user@hostname sslyze]$ pip install -r requirements.txt --target ./lib
    ...
    Exception:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
        status = self.run(options, args)
      File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 399, in run
        for item in os.listdir(lib_dir):
    OSError: [Errno 2] No such file or directory: '/tmp/tmpjEU1f_/lib/python/'
    [user@hostname sslyze]$ find /tmp/tmpjEU1f_/
    /tmp/tmpjEU1f_/
    /tmp/tmpjEU1f_/lib64
    /tmp/tmpjEU1f_/lib64/python
    /tmp/tmpjEU1f_/lib64/python/nassl-0.13.4-py2.7.egg-info
    /tmp/tmpjEU1f_/lib64/python/nassl-0.13.4-py2.7.egg-info/installed-files.txt
    /tmp/tmpjEU1f_/lib64/python/nassl-0.13.4-py2.7.egg-info/PKG-INFO
    /tmp/tmpjEU1f_/lib64/python/nassl-0.13.4-py2.7.egg-info/top_level.txt
    /tmp/tmpjEU1f_/lib64/python/nassl-0.13.4-py2.7.egg-info/dependency_links.txt
    /tmp/tmpjEU1f_/lib64/python/nassl-0.13.4-py2.7.egg-info/SOURCES.txt
    /tmp/tmpjEU1f_/lib64/python/nassl
    /tmp/tmpjEU1f_/lib64/python/nassl/__init__.pyc
    /tmp/tmpjEU1f_/lib64/python/nassl/ssl_client.pyc
    /tmp/tmpjEU1f_/lib64/python/nassl/debug_ssl_client.pyc
    /tmp/tmpjEU1f_/lib64/python/nassl/x509_certificate.pyc
    /tmp/tmpjEU1f_/lib64/python/nassl/ocsp_response.pyc
    /tmp/tmpjEU1f_/lib64/python/nassl/__init__.py
    /tmp/tmpjEU1f_/lib64/python/nassl/ssl_client.py
    /tmp/tmpjEU1f_/lib64/python/nassl/debug_ssl_client.py
    /tmp/tmpjEU1f_/lib64/python/nassl/x509_certificate.py
    /tmp/tmpjEU1f_/lib64/python/nassl/ocsp_response.py
    /tmp/tmpjEU1f_/lib64/python/nassl/_nassl.so

I have not been able to find a workaround using pip, so the best that I can do is this:

1.  git clone https://github.com/nabla-c0d3/nassl
1.  cd nassl
1.  mkdir install_root
1.  python2.7 setup.py install --prefix=./install_root
1.  mkdir /path/to/sslyze/lib
1.  cp -r install_root/lib64/python2.7/site-packages/nassl /path/to/sslyze/lib

**Comment by nabla-c0d3** [comment]
This is strange because nassl's setup.py is fairly straightforward, and does not touch things like how pip instals the library. Not sure if that's even possible but could it be that your python2.7 is 32 bits and your pip is 64 bits ?

**Comment by rdegraaf** [comment]
It looks like it's a bug in pip: https://github.com/pypa/pip/issues/3056.  Apparently the library path is hard-coded to "lib" in some key place. I haven't been able to test the work-around suggested in that bug report because I haven't been able to find a way to get pip to install from a local directory (--editable doesn't work with --local: https://github.com/pypa/pip/issues/562).

FYI, pip is a Python script, not a native binary.

**Comment by nabla-c0d3** [comment]
Sounds good - thanks for figuring it out!
