### ISSUE TITLE
do not download sources if a directory already exist

### ISSUE THREAD

**Issue by blshkv** [nabla-c0d3/nassl#42]
I'm packaging this tool to pentoo and need to compile it in a sandbox env.
We do not allow tools to download or install anything on its own so I have to download openssl/zlib tools in advance and place them into "deps" directory.

However, the current build_tasks script does not validate that and downloads it even if it is already exists.

Please do not overwrite it or make fetching function optional

**Comment by nabla-c0d3** [comment]
You can now use `invoke build.all --do-not-clean`
