### ISSUE TITLE
Rock64 aarm64 build fails

### ISSUE THREAD

**Issue by digitalhuman** [nabla-c0d3/nassl#44]
Hi there,

I am trying to build the 1.1.3 version from scratch on Debian 9. I keep getting the same error. Whatever version I get the same error. I could successfully build

https://www.zlib.net/fossils/zlib-1.2.11.tar.gz
https://github.com/PeterMosmans/openssl/blob/1.0.2-chacha

By following the https://github.com/PeterMosmans/openssl/blob/1.0.2-chacha/INSTALL guide.

But when building the 1.1.3 version of sassl I keep getting the below error:

```
nassl-1.1.3# aarch64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-T7HGOX/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-T7HGOX/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-aarch64-2.7/nassl/_nassl/nassl.o build/temp.linux-aarch64-2.7/nassl/_nassl/nassl_SSL_CTX.o build/temp.linux-aarch64-2.7/nassl/_nassl/nassl_SSL.o build/temp.linux-aarch64-2.7/nassl/_nassl/nassl_X509.o build/temp.linux-aarch64-2.7/nassl/_nassl/nassl_errors.o build/temp.linux-aarch64-2.7/nassl/_nassl/nassl_BIO.o build/temp.linux-aarch64-2.7/nassl/_nassl/nassl_X509_EXTENSION.o build/temp.linux-aarch64-2.7/nassl/_nassl/nassl_X509_NAME_ENTRY.o build/temp.linux-aarch64-2.7/nassl/_nassl/nassl_SSL_SESSION.o build/temp.linux-aarch64-2.7/nassl/_nassl/openssl_utils.o build/temp.linux-aarch64-2.7/nassl/_nassl/nassl_OCSP_RESPONSE.o build/temp.linux-aarch64-2.7/nassl/_nassl/python_utils.o bin/openssl-legacy/linux64/libssl.a bin/openssl-legacy/linux64/libcrypto.a bin/zlib/linux64/libz.a -o build/lib.linux-aarch64-2.7/nassl/_nassl_legacy.so -Wl,-z,noexecstack
/usr/bin/ld:bin/openssl-legacy/linux64/libssl.a: file format not recognized; treating as linker script
/usr/bin/ld:bin/openssl-legacy/linux64/libssl.a:1: syntax error
```

**Comment by nabla-c0d3** [comment]
Hello,
libssl.a is built for amd64, not arm so it cannot be used on your system. The latest version should work tho.

**Comment by digitalhuman** [comment]
I get the exact same error with the latest version

**Comment by nabla-c0d3** [comment]
What command did you use?

**Comment by digitalhuman** [comment]
I tried:  python setup.py
And:

pipenv install --dev
    $ pipenv shell

Nassl relies on a C extension to call into OpenSSL; you can compile everything using:

    $ invoke build.all

Then, the tests can be run using:

    $ invoke test

**Comment by digitalhuman** [comment]
I have tried with almost every version of Python.  These are the most common errors when trying to build.

SyntaxError: invalid syntax
(nassl-2.1.2) root@scanner:~/nassl-2.1.2# python3 build_tasks.py
  File "build_tasks.py", line 112
    return f'https://github.com/openssl/openssl/archive/{self._openssl_git_tag}.tar.gz'
                                                                                      ^
SyntaxError: invalid syntax
(nassl-2.1.2) root@scanner:~/nassl-2.1.2# python2 build_tasks.py
  File "build_tasks.py", line 59
    def __init__(self, platform: SupportedPlatformEnum) -> None:
                               ^
SyntaxError: invalid syntax

/usr/bin/ld:bin/openssl-legacy/linux64/libssl.a: file format not recognized; treating as linker script
/usr/bin/ld:bin/openssl-legacy/linux64/libssl.a:1: syntax error

**Comment by necrose99** [comment]
https://github.com/nabla-c0d3/nassl/issues/39
