### ISSUE TITLE
Can't install on os x

### ISSUE THREAD

**Issue by rfzabick** [nabla-c0d3/nassl#47]
I tried to install this with pip, and get the following output:

$ pip install nassl
Collecting nassl
  Using cached nassl-0.15.1.tar.gz
Requirement already satisfied: typing in /Users/rzabicki/turnip/lib/python3.5/site-packages (from nassl)
Requirement already satisfied: enum34 in /Users/rzabicki/turnip/lib/python3.5/site-packages (from nassl)
Installing collected packages: nassl
  Running setup.py install for nassl ... error
    Complete output from command /Users/rzabicki/turnip/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/hl/1nm8lk8n2cn7wwhzq0vf0jj80000gp/T/pip-build-bp54rdib/nassl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/hl/1nm8lk8n2cn7wwhzq0vf0jj80000gp/T/pip-bd7liz89-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/rzabicki/turnip/include/site/python3.5/nassl:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.5
    creating build/lib.macosx-10.6-intel-3.5/nassl
    copying nassl/__init__.py -> build/lib.macosx-10.6-intel-3.5/nassl
    copying nassl/ssl_client.py -> build/lib.macosx-10.6-intel-3.5/nassl
    copying nassl/debug_ssl_client.py -> build/lib.macosx-10.6-intel-3.5/nassl
    copying nassl/x509_certificate.py -> build/lib.macosx-10.6-intel-3.5/nassl
    copying nassl/ocsp_response.py -> build/lib.macosx-10.6-intel-3.5/nassl
    running build_ext
    building 'nassl._nassl' extension
    creating build/temp.macosx-10.6-intel-3.5
    creating build/temp.macosx-10.6-intel-3.5/nassl
    creating build/temp.macosx-10.6-intel-3.5/nassl/_nassl
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ibin/openssl/include -Inassl/_nassl -I/Users/rzabicki/turnip/include -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c nassl/_nassl/nassl.c -o build/temp.macosx-10.6-intel-3.5/nassl/_nassl/nassl.o -Wall
    nassl/_nassl/nassl.c:45:9: error: non-void function 'init_nassl' should return a value [-Wreturn-type]
            return;
            ^
    nassl/_nassl/nassl.c:50:9: warning: implicit declaration of function 'Py_InitModule3' is invalid in C99 [-Wimplicit-function-declaration]
        m = Py_InitModule3("_nassl", nassl_methods, "Nassl internal module.");
            ^
    nassl/_nassl/nassl.c:50:7: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
        m = Py_InitModule3("_nassl", nassl_methods, "Nassl internal module.");
          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 warnings and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Users/rzabicki/turnip/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/hl/1nm8lk8n2cn7wwhzq0vf0jj80000gp/T/pip-build-bp54rdib/nassl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/hl/1nm8lk8n2cn7wwhzq0vf0jj80000gp/T/pip-bd7liz89-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/rzabicki/turnip/include/site/python3.5/nassl" failed with error code 1 in /private/var/folders/hl/1nm8lk8n2cn7wwhzq0vf0jj80000gp/T/pip-build-bp54rdib/nassl/

**Comment by rfzabick** [comment]
Embarassing user error. I was using the wrong virtualenv when I ran this.

**Comment by nabla-c0d3** [comment]
Yes, Python 3 is not supported yet =)
