### ISSUE TITLE
Can't install nassl 2.2.0 with Python 3.7

### ISSUE THREAD

**Issue by fbexiga** [nabla-c0d3/nassl#47]
When trying to install the new version (2.2.0) of nassl on Python 3.7 it returns the following error.

```
$ pip3 install nassl==2.2.0
Collecting nassl==2.2.0
  Could not find a version that satisfies the requirement nassl==2.2.0 (from versions: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3, 2.1.0, 2.1.1, 2.1.2)
No matching distribution found for nassl==2.2.0
```

With Python 3.6 however, it works.

**Comment by nabla-c0d3** [comment]
It should be fixed now. Thanks!

**Comment by FirefighterBlu3** [comment]
can this pip pkg be redone so it's not limited to a very specific version of Python for pip? (using 3.8)

```
┌[✗ david@Scott ~ 
└─> pip search nassl
nassl (2.2.0)  - Experimental OpenSSL wrapper for Python 3.6+ and SSLyze.

┌[✓ david@Scott ~ 
└─> sudo pip install nassl==2.2.0
Collecting nassl==2.2.0
  ERROR: Could not find a version that satisfies the requirement nassl==2.2.0 (from versions: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3)
ERROR: No matching distribution found for nassl==2.2.0
```

**Comment by buhl-tax-service** [comment]
On Windows the same using 3.8:

> pip search nassl
nassl (2.2.0)  - Experimental OpenSSL wrapper for Python 3.6+ and SSLyze.
  INSTALLED: 1.0.3
  LATEST:    2.2.0

> pip install nassl==2.2.0
ERROR: Could not find a version that satisfies the requirement nassl==2.2.0 (from versions: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3)
ERROR: No matching distribution found for nassl==2.2.0

**Comment by epicfaace** [comment]
Same issue here -- do you know why this is happening? Do I need to switch to using a different version of pip?

**Comment by husnain-ce** [comment]
The issue is about python version.
