### ISSUE TITLE
Add support for Python3.8

### ISSUE THREAD

**Issue by dquitmann-op** [nabla-c0d3/nassl#50]
As Python3.8 was released on Oct. 14, 2019 (see https://www.python.org/downloads/release/python-380/), adding Wheels for it in the near future would be appreciated very much.

**Comment by schinkelg** [comment]
This would be very much appreciated. I can't get it installed using pip on python 3.8.

$pip search nassl
nassl (2.2.0)  - Experimental OpenSSL wrapper for Python 3.6+ and SSLyze.
  INSTALLED: 1.0.3
  LATEST:    2.2.0


$ pip install --upgrade nassl==2.2.0
ERROR: Could not find a version that satisfies the requirement nassl==2.2.0 (from versions: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3)
ERROR: No matching distribution found for nassl==2.2.0

**Comment by j4y4r** [comment]
Would be very nice to have the version 2.2.0 for python 3.8.
Any update on when to expect the enhancement?

**Comment by nabla-c0d3** [comment]
It's released now as version 3.0.0.
