### ISSUE TITLE
nassl 3.0.0 does not appear to be compatible with Python 3.9

### ISSUE THREAD

**Issue by kjjaeger** [nabla-c0d3/nassl#67]
Doing a pip install nassl using Python 3.9 appears to try to install nassl 1.0.3 instead of 3.0.0.

Trying to install nassl 3.0.0 with: pip install nassl==3.0.0 
results in this:
ERROR: Could not find a version that satisfies the requirement nassl==3.0.0 (from versions: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3)
ERROR: No matching distribution found for nassl==3.0.0

Even though pip search nassl returns this:
nassl (3.0.0)  - Experimental OpenSSL wrapper for Python 3.7+ and SSLyze.

Interesting that the very old nassl 1.0.3 seems to install fine, but nothing newer.  Is there a reason for that?

FYI, installing nassl 3.0.0 on Python 3.8.6 works just fine.

Thanks

**Comment by nabla-c0d3** [comment]
Hello,
Python 3.9 is not supported yet. This very old version of nassl does not have a C extension, so it can be installed (but won't work) on any version of Python.

**Comment by ahinrichs** [comment]
What is the reason for this? It builds without errors and sslyze seems to work with it under Python 3.9. At least for my use cases. Is there anything I probably could contribute to add support for 3.9?

**Comment by nabla-c0d3** [comment]
Fixed by having the wheels built automatically via GitHub Actions and enabling Python 3.9: https://github.com/nabla-c0d3/nassl/blob/release/.github/workflows/build_wheels.yml

**Comment by nabla-c0d3** [comment]
Fixed in v4.0.0.
