### ISSUE TITLE
Nassl 3.0.0 compatibility with Python3.8?

### ISSUE THREAD

**Issue by javixeneize** [nabla-c0d3/nassl#68]
Hi

Is Nassl compatible with python 3.8? Im having this error

ImportError: dlopen(/Users/javi/Library/Python/3.8/lib/python/site-packages/nassl/_nassl.cpython-38-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/javi/Library/Python/3.8/lib/python/site-packages/nassl/_nassl.cpython-38-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/javi/Library/Python/3.8/lib/python/site-packages/nassl/_nassl.cpython-38-darwin.so

Thanks

**Comment by nabla-c0d3** [comment]
Hello,
How did you install nassl and which version of macOS are you running?

**Comment by javixeneize** [comment]
Hi
I have high Sierra 
I installed it as a dependency of sslyze via pip. Looks like it’s related to the Xcode version

I downgraded python to 3.7.7 and again I had another error saying there is no package available for this distribution. 

Thanks

**Comment by rushter** [comment]
You need to compile it from scratch. This happens because you are running an outdated macOS (from 2017).
Newer versions of macOS changed some APIs and precompiled wheels will not work In some cases.

I had the same problem and compiling from scratch works as expected.

**Comment by nabla-c0d3** [comment]
Fixed by having the macOS wheels built automatically via GitHub Actions: https://github.com/nabla-c0d3/nassl/blob/release/.github/workflows/build_wheels.yml

**Comment by nabla-c0d3** [comment]
Fixed in v4.0.0.
