### ISSUE TITLE
Alpine not able to find nassl 4.0.0 to install

### ISSUE THREAD

**Issue by jauderho** [nabla-c0d3/nassl#80]
When trying to build an Alpine based container image of sslyze, it looks like it is not able to find the 4.0.0 version (even if I specify it explicitly)

I get the error

```
ERROR: Could not find a version that satisfies the requirement nassl==4.0.0
ERROR: No matching distribution found for nassl==4.0.0
```

I tried skipping the wheel by using no-binary but pip still picks 1.0.3

```
Collecting nassl
  Downloading nassl-1.0.3.tar.gz (30.0 MB)
Skipping wheel build for nassl, due to binaries being disabled for it.
Installing collected packages: nassl
    Running setup.py install for nassl: started
```

But since sslyze 4.1.0 is incompatible with nassl 1.0.3, the build fails. It looks like something needs to be changed to teach pip about nassl 4.0.0

**Comment by nabla-c0d3** [comment]
Hello,
Alpine is not officially supported as a platform. You could try compiling nassl from scratch and see what happens.
