### ISSUE TITLE
nassl is unnecessary, even for SSLyze - pyOpenSSL works for all native OpenSSL methods

### ISSUE THREAD

**Issue by chrisdlangton** [nabla-c0d3/nassl#81]
per README

```md
Why another SSL library?
------------------------

I'm the author of [SSLyze](https://github.com/nabla-c0d3/sslyze), an SSL scanner written in Python. Scanning SSL servers
requires access to low-level SSL functions within the OpenSSL API, for example to test for things like insecure
renegotiation or session resumption.

None of the existing OpenSSL wrappers for Python (including ssl, M2Crypto and pyOpenSSL) expose the APIs that I need for
SSLyze, so I had to write my own wrapper.
```

This is fundamentally untrue.  You mistake **convenience methods** of `pyOpenSSL` as the extent of it's bindings. Ergo you fail to acknowledge `pyOpenSSL` offers full support for all low level native `OpenSSL` methods with a limited subset of **convenience methods** - therefore you chose to re-implement a python binding so you can have more **convenience methods** instead of adding your **convenience methods** as a pull request upstream to `pyOpenSSL`

Allow me to demonstrate how you can access a low level native `OpenSSL` method using `pyOpenSSL` even when there are no python **convenience methods** available:

```py
from OpenSSL.SSL import _lib as native_openssl

# conn = SSL.Connection
# https://www.openssl.org/docs/man1.1.0/man3/SSL_SESSION_has_ticket.html
session_tickets = native_openssl.SSL_SESSION_has_ticket(conn.get_session()._session) == 1
# https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_get_session_cache_mode.html
session_cache_mode = native_openssl.SSL_CTX_get_session_cache_mode(conn._context._context)
# https://www.openssl.org/docs/man1.1.1/man3/SSL_SESSION_get_ticket_lifetime_hint.html
session_ticket_hints = native_openssl.SSL_SESSION_get_ticket_lifetime_hint(conn.get_session()._session) > 0
```

This is only 3 examples, though I see no limitation that any low level native `OpenSSL` method would be impossible as you claim.

Furthermore, all of these examples would make a great PR to `pyOpenSSL` as we all would like more **convenience methods**, it is the open source way right?

**Comment by nabla-c0d3** [comment]
You don't know this project and SSLyze well enough to understand why nassl was needed ~8 years ago when I wrote this paragraph in the README, and why it is still needed today. Maintaining an OpenSSL wrapper is a PITA and I wouldn't do it if I didn't have to.
I'm also unsure about the point of your message.
