### ISSUE TITLE
DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats

### ISSUE THREAD

**Issue by PhilippSelenium** [nabla-c0d3/nassl#82]
```
python3.8/site-packages/nassl/ssl_client.py:197: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
```
Code: https://github.com/nabla-c0d3/nassl/blob/release/nassl/ssl_client.py#L197

Info: https://python.readthedocs.io/en/stable/c-api/arg.html#strings-and-buffers

**Comment by nabla-c0d3** [comment]
Fixed in https://github.com/nabla-c0d3/nassl/pull/87/commits/9b3bd017c9887499c47ce50cb8c0d4f5c205261d
