### ISSUE TITLE
Homebrew: nassl-{version}.tar.gz file missed in the pypi index

### ISSUE THREAD

**Issue by chenrui333** [nabla-c0d3/nassl#88]
👋  it would be great that the nassl-{version}.tar.gz file can also be uploaded into the pypi index as it is needed for [the homebrew formula build](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sslyze.rb#L13-L16). Thanks!

**Comment by entropymatters** [comment]
Providing an sdist on Pypi would also be much appreciated from my side, in order to ease the build steps needed for a pyodide package.

**Comment by nabla-c0d3** [comment]
The build process for nassl is not easy to implement as part of a source distribution. 

Also, I'm personally not in favor of providing one because it will increase the support requests when the source distro does not build or work (for example on a very exotic environment).

**Comment by entropymatters** [comment]
Thanks for consideration, for my use case a release from GitHub worked well.
